require('dotenv').config();
const express = require('express');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors()); app.use(express.json());
app.use('/api/auth',      require('./routes/auth'));
app.use('/api/incidents', require('./routes/incidents'));
app.use('/api/knowledge', require('./routes/knowledge'));
app.use('/api/search',    require('./routes/search'));
app.use('/api/reports',   require('./routes/reports'));
app.use('/api/pir',       require('./routes/pir'));
const { router: auditRouter } = require('./routes/audit');
app.use('/api/audit', auditRouter);
app.get('/api/health', (req,res) => res.json({ status:'ok', time: new Date().toISOString() }));
app.use((err,req,res,next) => { console.error(err.stack); res.status(500).json({ error:'Internal server error' }); });
app.listen(PORT, () => console.log('KALRO IKF running on http://localhost:'+PORT));
